class ZodiacSign {
  final String name;

  final String description;

  ZodiacSign({
    required this.name,
    required this.description,
  });
}
List<ZodiacSign> zodiacSigns = [
  ZodiacSign(
    name: 'koc',
    description:
    'Ateş grubuna dahil olan Koç burçları çevrelerinde yüksek enerjileri ve girişimci ruhlarıyla tanınırlar. Öncü burçlardan oldukları için atılgan yapılarıyla ön plana çıkabilirler. Bir işe başlamak için her zaman fikirleri ve enerjileri vardır.',

  ),
  ZodiacSign(
    name: 'boga',
    description: 'Toprak grubuna dahil olan Boğa burçları sakin yapıları ve güvenilir olmalarıyla bilinirler. Keskin bir maddi zekaları vardır. Venüs’ün yönetiminde olduklarından ötürü hayatın güzelliklerine düşkündürler. Bir şeyin estetik olarak göze güzel görünmesine önem verirler. Hayatlarını huzurlu ve güzel bir şekilde yaşamaları için paranın öneminin farkındadırlar. Para kazanmak onlar için şöhret veya üstünlük için değil, dört dörtlük istedikleri kalitede bir yaşam yaşamaları için önemlidir. Sabırlı bir burçtur. Zorluklar karşısında bu sabrı sayesinde ayakta kalırlar. Yavaş ve emin adımlarla ilerler. Garanticidirler, riskli işler varsa kendilerini geri çekerler. İştahları açıktır. Herhangi bir yemek değil, güzel bir yemek onları mutlu eder. Yedikleri öğünler kaliteli ve tatları güzel olmalıdır. Sofrada her şey göze hitap etmelidir. Lüksüne düşkün bir burçtur. Pahalı ve modaya uygun kıyafetleri tercih ederler. Mücevherlere de düşkünlükleri olabilir. Kazandıkları paraları hemen harcamak yerine daha iyi getirisi olan yatırımlara yatırabilirler. Garantici olduklarından ötürü önce para biriktirir, sonra lüksüyle ilgili harcamaları yaparlar. Sakin bir burç olmasına rağmen sinirlendiğinde bir Boğa burcunun yanında bulunmak istemezsiniz. Fevri değildir ama sabrı taştığında öfkesi tahmin edilemeyecek boyutlara varabilir. İnatçıdırlar. Aşkın, tutkunun da önemli olduğu burçlardan biridir. Sadece aşkı körü körüne değil, hayat kalitesi olarak kendilerini taşıyabilecek bir partnerle yaşamak isterler.',

  ),
  ZodiacSign(
    name: 'ikizler',
    description: 'Hava grubuna ait olan İkizler burcu neşesiyle, pozitifliğiyle ve pratik zekasıyla bulunduğu çevrede tanınırlar. İletişim kurma becerileri gelişmiştir. Her zaman herkesle rahatça anlaşabilirler. Konuşarak, sempatik tavırlarıyla çözemeyecekleri sorun yoktur. Sosyal yönleri güçlüdür. Eğitime önem verirler. Yaşları kaç olursa olsun her zaman öğrenmeye meraklıdırlar. Bu sadece akademik anlamda değil hayata dair her şeyi bilmek isterler. Her konu hakkında bir miktar bilgileri vardır. Bulunduğu çevre ne kadar farklı olursa olsun mutlaka o ortamla ilgili konuşacak bilgiye sahiptirler. Kültür seviyeleri yüksektir. Kitaplara, yazmaya düşkündürler. Edebiyata ilgi duyarlar. El becerilerine çok yatkındırlar. Fikirlere önem verirler. Her zaman dostlarıyla düşüncelerini paylaşır, akıl danışmayı severler. Zekaları yüksek olduğu için zihinleri çoğu zaman karışıktır. Birçok düşünce saniyeler içerisinde akıllarından geçer. Bu durum da bu burcun karakteristik özelliği olan kararsızlık sorunlarını meydana getirir. Yeri geldiğinde kendi aldıkları kararları bile anında değiştirebilirler. Konuşmayı çok severler. Paradan çok insan ilişkilerine önem verirler. En büyük zenginlikleri etrafındaki insanlardır. Parayı bir şekilde kazanabileceklerini düşünürler. Belirli kalıplara göre yaşamayı sevmezler. Anı yaşamak, hayatın tadına varmak daha önemlidir. Etrafındakilere yardımcı olmayı severler. Bazen bu durum kendilerini arka plana atmalarına sebep olabilir. Değişken tavırları ve düşünceleri ile hayatlarında önemli kararlar almakta zorlanabilirler.',

  ),
  ZodiacSign(
    name: 'yengec',
    description: 'Su grubuna ait olan Yengeç burçları duygusal yapıları ve ailelerine düşkünlükleriyle bilinirler. Annelik denildiğinde Yengeç burcu akla gelir. Her zaman kendinden önce sevdiklerinin ve çocuklarının güvende olmaları onlar için önemlidir. Sevgiye, güvene çok değer verirler. Bu verdikleri değeri de aynı şekilde karşı taraftan beklerler. Hiç karşılık beklemeden kendilerini adayabilirler. Onlar için her şeyin huzur içinde ilerlemesi önemlidir. Hisleri çok kuvvetlidir. Duygusal hayatlarında hep güven arayışı içindedirler. Bu durum bazen kıskanç olmalarına neden olabilir. Duygusal olmaları bazen karamsarlığa sürükleyebilir. Kırılgan yapıları olduğundan kimseye belli etmeden içerleyebilirler. Zaman zaman içlerine kapanabilirler. Ne yaşadıkları dışarıdan anlaşılmasa da içlerinde büyük fırtınalar kopuyor olabilir. Milliyetçi duyguları ön plandadır. Yaşadığı ülkeye, bölgeye sahip çıkarlar. Gelenekselci yapıları vardır. Köklerinden getirdikleri gelenekleri sürdürmeyi severler. Eski her zaman onlar için bir yol göstericidir. Bu eskiye bağlılık bazen modern dünyaya şüpheci bakmalarına neden olabilir. Yuva kurmak Yengeç burçları için önemlidir. İçgüdüsel olarak bu eğilimde olmaları bazen hatalı tercihler yapmalarına neden olabilir. İyi niyetleri suistimal edilebilir. Dostluk ilişkileri önemlidir. Evlerinde vakit geçirmeyi, misafir ağırlamayı severler. Yemek yapmaya yetenekleri vardır. El lezzetleri mükemmeldir. Muhtemelen birine yemeğe misafirliğe gidiyorsanız bu Yengeç burcu olmalıdır. Kesinlikle doymadan kalkamazsınız.',

  ),
  ZodiacSign(
    name: 'aslan',
    description: 'Ateş grubuna ait olan Aslan burçları liderlik özellikleri ve gururlu yapılarıyla dikkatleri çekerler. Yönetme yetenekleri bir hayli fazladır. Kendine güveni olan bir burçtur. Güçlü bir karakteri vardır. Gurur her şeyden önce gelir. Sahne, ün ve şöhretle ilişkilendirilirler. Genellikle medyatik kişiler ve liderler bu burçtan çıkar. Bulunduğu çevrede en güçlü ve en başarılı olan kişinin kendisi olmasını ister. Hırslıdır. Bazen hırslı yapısı sinirlerine hakim olmasında zorluk çıkartır. Dobra tavırları karşı tarafı kırabilir. Cesur tavırları, inandıkları uğrunda taviz vermemeleri ve dürüstlükleri ile belli bir duruşa sahiptirler. Sevgiye, aşka önem veren bir burçtur. Tutkuludur. Cinselliğe önem verir. İş hayatında yükselmek, terfi almak önemlidir. Her zaman en tepede olmayı hayal ederler. Özgüvenlerinin yüksek olması, kendilerini ön plana atmaları, övmeleri bazen topluluk içerisinde tepki almalarına neden olabilir. Bunun sebebi Aslan burçlarının hiçbir zaman geride kalabilecek bir karakterde olmamalarından kaynaklanır. Her zaman en iyisi ve en güzeli hayatlarında yer almalıdır. Lükse düşkündürler. Para konusunda tutumlu olsalar da konu marka veya popüler bir şey almak olduğunda kesenin ağzını açarlar. Fiziki görünüşlerine dikkat ederler. Her zaman bakımlıdırlar. Yanında olan kişinin de her zaman fiziksel olarak güzel olması gerekir. Çünkü onlar için hayat bir bütündür ve her şey görkemli olmalıdır.',
  ),
  ZodiacSign(
    name: 'basak',
    description: 'Toprak grubuna üye olan Başak burçlarını çalışkanlığı, disiplinli tutumları ve ince ayrıntılara verdikleri önemlerden tanıyabilirsiniz. Merkür’ün yönetimde oldukları için öğrenmeye olan merakları sebebiyle diğer kişilerin dikkat etmedikleri en ufak noktalara dikkat ederler. Çalışma hayatlarında başarılı olmalarının sebebi de ince ayrıntılara verdikleri önemden dolayı işlerini kusursuz yapmalarından kaynaklanır. İnce ve zarif düşünceli olduklarından ötürü karşı taraftan da aynı özveriyi beklerler. Eleştirmeyi, fikir vermeyi severler. Bu durum bazen karşı tarafın işine çok karıştıklarına dair sitemlere yol açabilir. Hayatlarında her şeyin sistematik bir düzende olmasını isterler. Titizlerdir, özensiz hiçbir şeye tahammül edemezler. Çalışmaktan asla bıkmazlar. Para kazanmak için her meslekte başarılı olabilirler. Çünkü onlar her işin altından kalkabilirler. Çalışkan yapıları zekalarıyla birleştiğinde başarılı iş insanı olarak toplumda öne çıkabilirler. Zihinleri bazen çok negatife odaklandığında Başak burçlarının kuruntuları ortaya çıkar. Zihinlerinde kurdukça adeta kendi enerjilerini nedensiz yere düşürebilirler. Boş hayallere kapılmazlar. Her zaman gerçekçidirler. Önce en kötü ihtimalleri düşünmeleri yaptıkları işlerde güvenilir olmalarını sağlar. Dostları tarafından sevilen bir burçtur. Evine ve yuvasına önem verir. Kendilerine bakmayı, bakımlı görünmeye dikkat ederler. Her şeyin uyum içinde olmasına dikkat ederler. Her konuda mükemmele odaklıdırlar. Bu nedenle hayatlarında mutluluğu yakalamaları zor olabilir.',

  ),
  ZodiacSign(
    name: 'terazi',
    description: 'Hava grubuna ait Terazi burçları nazik, güler yüzlü ve güzelliklerine düşkün olmalarıyla bulundukları ortamda dikkatleri çekerler. Her zaman pozitif enerji saçan bu burç, hayatın güzelliklerine kendini adamıştır. Onun için her şeyin estetik bir yanı olmalıdır. Venüs’ün yönetiminde oldukları için hem kadınlarında hem erkeklerinde tarifi olmayan bir çekicilik vardır. Nedenini bilemediğiniz bir şekilde Terazi burcunun sizi mıknatıs gibi kendisine çektiğini hissedebilirsiniz. Hayatlarında hep bir denge arayışı vardır. Her şey onlar için eşit seviyede olmalıdır. Belli bir duygu veya madde başka bir şeyin önüne geçmemelidir. Hava grubu olan bu burç dengesi bozulduğunda kararsızlıklar da yaşamaya başlayacaktır. Hoşgörülü ve adildir. Eşitlik duygusuna önem verir. Kimseye ayrımcılık yapmak istemez. Haksızlıklar karşısında tahammülü yoktur. Sosyal bir bireydir. Dostlarıyla beraber oldukça enerjisi de artar. Eğlenmek, hayatın güzel tarafını görmek öncelikleridir. Keyifli bir hayata düşkünlükleri bazen iş hayatını bırakmalarına ya da tembel olmalarına sebep olabilir. Bu burcun bir diğer özelliği de ilişkileri ve evlilikleri temsil etmesidir. İkili ilişkiler denildiğinde Terazi burcu sözü devralır. Hem duygusal hem iş ilişkisinde kibardır. Kurduğu iletişim sayesinde karşı tarafı etkiler. Sevgiye önem verir. İlişkilerin ve sevginin temsili bu burç bazen duygularını frenlemekte zorluklar çekebilir. Güzel olan her şey gibi sanata olan düşkünlükleri de oldukça fazladır.',

  ),
  ZodiacSign(
    name: 'akrep',
    description: 'Su grubu Akrep burçları etkileyici bakışları, gizemli ve güçlü karakterleriyle bulundukları ortamlarda hemen dikkati çekerler. Çoğu zaman sessizlikleriyle ön plana çıkan Akrep burçları az ve öz konuşurlar. Bazı şeyleri açıkta yaşamak yerine içlerinde tutmayı isterler. Tam olarak onların ne düşündüklerini çözemezsiniz. Duygularını gizleme konusunda başarılıdırlar. Buna rağmen aslında duygusal bir burçtur. Sevdi mi çok sever. Fakat onlarla düşman olmak istemezsiniz. Kinleri ve intikam alma güçleri çok fazladır. Ona yapılanların karşılığını vermek için bazen yıllarca sabrederler. Gururlu ve cesur karakterde bir burçtur. Asla yalanlara göz yummaz. Kendi gibi herkesin güçlü karaktere sahip olmasını bekler. Hisleri çok kuvvetlidir. Bazen sezgilerinin yönlendirmesiyle her şeyi açığa çıkartır. Rüyaları çıkan bir burçtur. Güven duygusu Akrep burçları için önemlidir. İş veya gönül ilişkisinde ilk baktığı şey güvenmektir. Güvenmediği anda kuşkucu yapısı onları ele geçirir. Sürekli kuşku duyduğundan insanlara tamamen duygularını açıklamakta zorlanır. Bu durum kıskanç olmalarına da neden olur. Şüpheci tavrı diğer alanlarda ise başarı getirir. Araştırmacı özellikleri iş ve eğitim hayatında onları bir adım öne çıkartır. Ölüm, ölümden sonraki gizem ilgilerini çeker. Korku, gerilim, suç filmlerine karşı ilgileri vardır. Duygularını zirvede yaşadıklarından çok tutkulu olurlar. Cinsellik hayatlarında önemli bir yer taşır.',

  ),
  ZodiacSign(
    name:'yay',
    description: 'Sevgili Yay burçları, hiç beklemediğiniz kişilerle aranızda gerginlik yaşabilir ve kendinizi bir anda tartışmaların ortasında bulabilirsiniz. Ruh halinizin bugün değişkenlik gösterdiğini fark edeceksiniz. Rutinlerinize bağlı kalmak arzusu içinde olsanız bile bazı sapmalar yaşayabilirsiniz. Çatışmanın ilişkilerin doğal bir parçası olduğunu kabul ederek iletişim yeteneklerinize güvenin.',

  ),
  ZodiacSign(
    name: 'oglak',
    description: 'Toprak grubunun üyelerinden olan Oğlak burcu çalışkanlığı, ciddiyeti ve sabrıyla ilk başta dikkat çeker. Hayattaki her konuya ciddi yaklaşırlar. Bulundukları ortamlarda mesafeli tavırları dikkat çeker. Hemen samimi olmayı sevmeyen kişilerdir. Liderlik vasıfları çok yüksektir. Analitik düşünce yapıları ve çalışkanlıkları sayesinde diğer kişilerden daha fazla vizyona ve birikime sahip olabilirler. Aceleci değildirler. Sabrettiklerinde istediklerinin gerçek olacağını bilirler. Hızlı davranmanın hatalar getireceğini düşünürler. Hayatlarında hep bir hedef ve buna ulaşma çabası vardır. Çalışkanlıkları ve zorluklar karşısında yılmayan tavırlarıyla her zaman akıllarına koydukları şeye ulaşırlar. İş hayatlarında mükemmel olmayı isterler. Bu durum beraber çalıştığı kişiler için zor olabilir. Kendi gibi kusursuz ve saatlerce emek verebilecek insanlar ararlar. Bunu görmeyince ise sinirlenmeye başlarlar. Otoriter bir tavırları vardır. Duyguların pek fazla yeri yoktur. Hayat bir plandır ve bu planın işlemesi için duygulardan uzak durmaları gerektiğini düşünürler. Hırslı yapıları bazen kendilerine zarar verir. Bir meseleyi çözene kadar hayattaki diğer unsurları devre dışı bırakabilirler. Bu konu aileleri tarafından eleştiri alabilir. Yalnızlığı severler. Kalabalıklar onlara göre değildir. Bazen en yakın arkadaşı kendileri olurlar. Maddiyata önem verirler. Savurganlığı sevmezler. Mantığın her şeyi çözebileceğini düşünen bu burç duygularını belli etmede zorluklar yaşayabilir.',

  ),
  ZodiacSign(
    name: 'kova',
    description: 'Hava grubunun temsilcilerinden olan Kova burçları marjinal tavırlarıyla, özgürlüklerine düşkünlükleriyle ve zekalarıyla bilinirler. Gerek fikirleriyle gerek dış görünüşleriyle bulundukları ortamda dikkatleri üzerlerine çekerler. Fikirlerde sabit olan Kova burçları, dik kafalı olduklarına dair eleştiriler alabilir. Fakat bu fikirlerde sabitlik tarih boyunca ünlü bilim adamlarının ve kadınlarının bu burçtan çıkmasını sağlamıştır. Akıllarına koyduklarının elbet bir gün doğru olacaklarına inanmaları sürekli aynı şeyi deneyip, yılmadan çalışmaları büyük keşifleri de beraberinde getirmiştir. Fikirlerine çok güvenmeleri bazen hayattan kendilerini soyutlamalarına neden olabilir. Sürekli düşündükçe işin içinden çıkamaz hale gelirler. Aklın üstünde olduğu bu burcun fazla düşünmesi, psikolojik problemlere sebep olabilir. Günlük dertler onların ilgi alanına girmez. Toplumu değiştirmek, insanlığa fayda sağlamak isterler. Her zaman modern çağa ayak uydururlar. Yeniliklere hayır demezler. Özgürlüklerine düşkün olmaları her an her şeyi yapabilecekleri anlamına gelir. Bir anda işi bırakabilirler. Aynı durumu ilişkide de yapabilirler. Konu ne olursa olsun kısıtlanmayı sevmezler. Bu hayatta idealleri vardır. Etrafındaki insanlar da akıllı olmalıdırlar. Onların dediklerini anlamayan ya da hayatta amacı olmayan insanlarla işleri olmaz. İlişki konusunda bağlanmakta zorlanabilirler.',

  ),
  ZodiacSign(
    name: 'balik',
    description: 'Su grubuna dahil olan Balık burçları duygusal yapıları, şefkatli tavırları ve geniş hayal güçleriyle kendilerini gösterirler. İnsani değerlere önem veren bu burcun bireylerinin empati yetenekleri çok gelişmiştir. Her zaman kendilerinden çok başkalarına önem verirler. Yardımseverlerdir. Kendileri ne kadar zor durumda olurlarsa olsunlar başkasına yardım etmek onları manevi olarak güçlendirir. Yaptıkları iyiliklerle bu dünyada yer edeceklerini düşünürler. Hırsın, paranın, şöhretin geçici olduklarını bilirler. Çok iyilik yapsalar da aynı karşılığı çoğu zaman bulamazlar. Yumuşak kalpli ve affedici olmaları insanlar tarafından kullanılabilir. Çok yetenekli olmalarına rağmen kendilerini övmezler. Hayalleri vardır. Güzel bir hayat için sürekli düşler kurarlar. Estetiğe, güzelliğe önem verirler. Evleri, sofraları, bulundukları çevre göze hitap etmelidir. Sanata yatkındılar. Duygularını o kadar yoğun yaşarlar ki bunun derinliğini kimse anlayamaz. Bu içten duygular, yetenekleriyle birleşince ünlü bestecilerin bu burçtan çıktığına şaşırılmamalıdır. Alkole düşkünlükleri olabilir. Sevdikleri her şey için kendilerini adarlar. Hisler denilince Balık burcundan bahsetmemek olmaz. İnanılmaz derecede güçlü sezgileri vardır. Hisleri her zaman çıkar. Medyumlar, falcılar bu burcun temsilindedir. Aşk hayatlarında romantik bir partner olurlar. Çok severler fakat kalpleri kırıldığında, içine düştükleri psikolojik buhrandan çıkmaları zor olabilir.',

  ),
];